language: python
python: 3.7
dist: xenial
sudo: true
script:
- pip install -r requirements.txt
- pip install pytest==4.6.3
- pip install decorator
- wget https://github.com/BurntSushi/ripgrep/releases/download/11.0.1/ripgrep_11.0.1_amd64.deb -O /tmp/ripgrep
- sudo dpkg -i /tmp/ripgrep
- wget https://github.com/skylot/jadx/releases/download/v1.0.0/jadx-1.0.0.zip -O /tmp/jadx.zip
- unzip /tmp/jadx.zip -d /tmp/jadx
- sudo ln -s /tmp/jadx/bin/jadx /usr/local/bin/jadx
- java -version
- rg --version
- jadx --version

- pytest --disable-pytest-warning

cache: pip
notifications:
  slack:
    secure: vM6MO1lZ8iVkbpgLGlvjPXBrq4XALgS/3nqOqXbUO8qSHxCbIeWSphalxvEpM1O2xkXLIayVMkaYECl5n9BLtYrcq4hV/FrKlBud03Mw9aAJcW1fTIuYQaFLYCdbhcfor1C/d3dZJ/eIGI9jL5wXSDNGn5XxWKnk27TbYZLDF/gq1t8zEe81aQ7BgioS1NV8+dpAWVPzySCaLwNENyIe0hxvGIj98wDKb6lot2XzpGwgcP1braIWQ2NTZxKY8rVpjShrLTikYrRLN/W/NbDpTx5f2MzvJqzjeU913HffpQsDVSQ06gbzClmq4yPVAB0yBjs2WjiYRGnhdh83ROESM3wy2SxGX51vKEP0hffK3A8W3rLtxxtlhOFPmw6ns6rWc//C42m5hZBlFnedmkNa8MB/MrGWXYFTJ61Tvq8xKxdq03nYfyhjlmoOSao3litIE5XkJky/51202oyS3NnbaL+BXgtPTU39zJf9s3LROK7XgkVTF8Wy03T3IugkU5xsseCfDQg+rTGj0SPcWMZTSigD9PEfJ6H1pKWM2K2L1JxrpKrsqzAnwpZR5IBDUyI46CJGyU+9QaNjbl72K5PBSxTrTGe2OVA6zYb24tYTyjj4FtGSGxmcNZBSjFeqrlu1XnC0wyvvYTnuBIze8aAB8XtT7IOZ9HfWy3Hvrgxz/sY=
deploy:
  provider: pypi
  user: securisec
  password:
    secure: N2U4g/+AkUN1RPJmcHYocSqFZiF/Td2E21tFuk6y+tG2E2Rzyk42pgyrUsczB06lC4x3sDwbsXM6hxxa78vidYBKLdV/1B2ONf3XonHzwsyqOTyrFZKILsNumVmk4pMj7qXOJvUMC88l1WFg7MJaw6XuDjTPD6iLcs0HlCuWXzLFSxj6h0Q6hAtaoRDWE4qF+uyYOoS1DqJauQk7X8IdPZDVQRO59SwLKh/QkLQe8pux/2hETMLyn9BgGnjPIQpHKESH539pwOxYhI8tN3vl47JeI+DTo+AUMfQs+3S7K0n39BRhLKI3L09zu8Hh26X+VlJFrFHsolbk04439xy0sRteapLCJ4tCZ58GCyU2sL1nDB2qp4nMlEz5Bou5SM+x10Qc9bL4+MnCvE0v6f79qSYPDoAflRwPzwX703Dy9tZgiyHOFNks/u/aLhEHhp/KGyAv09khVkWqaeQQVIWrYnda2YXJ0xhd7gpqHgETnl3ilMbYpBXdkJwd8yS96ijBM5hPixxhdtSoi3C7aVcWoCGiS864y2gdrOkIdXYVzRz74hG097eSCph/84vBO0mjnuG094boUt/I9M4foRo+aPJN9MbSmNzqdQgGM6E7IpmOGjj4UgQiM2H6/mA1vtmwNoVOR/Qdij/iYzDRm50tssqBElx/jlxzbDJv/DTyXQw=
  on:
    tags: true
    distributions: sdist bdist_wheel
  skip_exisiting: true
  skip_cleanup: true
