language: python
python: 3.8
dist: xenial
sudo: true
script:
- pip install -r requirements.txt
- pip install pytest
- pip install decorator
- pip install -e .
- wget https://github.com/BurntSushi/ripgrep/releases/download/11.0.1/ripgrep_11.0.1_amd64.deb
  -O /tmp/ripgrep
- sudo dpkg -i /tmp/ripgrep
- wget https://github.com/skylot/jadx/releases/download/v1.0.0/jadx-1.0.0.zip -O /tmp/jadx.zip
- unzip /tmp/jadx.zip -d /tmp/jadx
- sudo ln -s /tmp/jadx/bin/jadx /usr/local/bin/jadx
- java -version
- rg --version
- jadx --version
- pytest --disable-pytest-warnings
cache: pip
notifications:
  slack:
    secure: G8pEdGESfzyRXwULNscENqT/hux41Mc6WVhRq/cZFdrCDLL4kmBCnXXY5L7Dt4HROMnqDYriCRB0KAaoOcOO28AvZGoAWWPCtfCktckzFoLRg31t1tUW4Pis48+jh/L22Z112HuOIlH+koY210i6HmbxpBnNrurkg4jo2f4ahlxnMGDEAeMeo3L5z5TdawafVPCS5Kb8kJoj4Wpvn/NWGylNOEtyL/tZ9rmEUQtXpl8xzy9PbEW5/51EaDBTPjZ7fZZoJ8I35HsstC9Z/nUuBTvJasrY35R6LtdnUc9jGBpDmwA/TvgO3Gbenh96uSOyuxHOAzVo4obeKmneUxI7PkCacfCm9WkY+NCcmJ4Sob3R1ao3iVJrmZ4o7tD46hrYsQsposX+ABADejmwvaOAsYBRr+ucKD/axMYQ5A5Un/DBCH3SM0Z4iUusAVPiRla9MrZJxBs/62EwSWLaEP1IgoxNbGpx6C86yTekkSoNUZJq+FnY+DtNksXKS53TgAzAvfEy778iNQJ4XrRkWLTSiZopTSga20S0QcosJCdCKePp+VsRwR+B8f1CBtSBQrumxnP/CSwHDdBbwHhkCJcEgcGHsr4mIhNlHBtW5xJfBvhrOtO/AtHfFzqwaKrUuOMRf7NMFklSJ990fdGgBknz7L2JUovo70hfXK3M2Pk//dU=
deploy:
  provider: pypi
  user: securisec
  password:
    secure: BA6OGUylc4qZ3SI+UNIlEW9a4KHChtVL7WD9iPrgJArQ4V4OSFfSoEtkK7NGzzd+dZPOs3MPs4SfvGxHE0ZBqAo6CI1MsN6/ZARYclFvM1w2mHVp7Y+xCFY4O2+qqT1J6p0yalJv1Ho6w1LSxbJSPslLhjFq/kAf8BxKUDIbv79Mp+k45UOsO9PcFK5OQyTkA0fX9WMu7Nh2aiaF436MlSliWh2VTF8bb+SAwbNM+pO4fkrWeWzf5e+3xkYUwcolQSgw9iDIR/PkTHf9/I5VAnpvXhDcNy4Pt5Tnm1C9DR7y+jVYx7i2v3JOhpT5JIthsFk+ED2c1UaYN/pEqoM3aT+f0Ezq7aC2BqEhjXuEVNGpVSOH/Ak/XZY0DlgCqLNygxj9tE2Cwz8nS5p5A7Ge54PkebB4CrgDYZk1FRl9eXhhHVm2EDG/V/Brdm/w+2uGcbFsX1BbhX+8I3pK/SsOTcAEZLvBgwukl+gTWJbVCKIyyhtMfMMJ1+8pUUZB8qQWlTB50azAZa690UNtno9xYSig2bkmz37Q2GpmQlqLBV28+YO+wMO22UQn4xH3K+pTwXtMHNyMYirYeA/D70ekNRclbumwVUmszU/8TqltzCkORYc3BoCqcwhkxx1tVz4anqiNXuDqhx7CVam0tA1Ryi3TTv5SEE16wAXaDK9Llgo=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: securisec/glorifiedgrep
  skip_existing: true
  skip_cleanup: true