language: python
python: 3.7
dist: xenial
sudo: true
script:
- pip install -r requirements.txt
- pip install pytest==4.6.3
- pip install decorator
- pip install -e .
- wget https://github.com/BurntSushi/ripgrep/releases/download/11.0.1/ripgrep_11.0.1_amd64.deb
  -O /tmp/ripgrep
- sudo dpkg -i /tmp/ripgrep
- wget https://github.com/skylot/jadx/releases/download/v1.0.0/jadx-1.0.0.zip -O /tmp/jadx.zip
- unzip /tmp/jadx.zip -d /tmp/jadx
- sudo ln -s /tmp/jadx/bin/jadx /usr/local/bin/jadx
- java -version
- rg --version
- jadx --version
- pytest --disable-pytest-warning
cache: pip
notifications:
  slack:
    secure: Tt7L7TroscMZ6pqDIrWh85prPnhmRLdUdcLbXX9hPNX4Yj+EB2woBOB1EUfvSzvlvbfp9aLp+EW7fZVt17qS3qBI68HHECnVJIFqGgxlg5Dx7FyZfye1rt3YQZ0ExXSzWOgUTKzb59Bdct9t1z/f3L4Iar5cWYiJlp5lb/DgBK2WaTmvoCC7Vx7GEhAANFJe4vKRfB9+NG5zM7zAapYIHYA1uYVuARscy6dyqIKvuPICucMCEHTayk5VICcrl9i+48YiJIfJp+lR2H08OB+Jsf1+4yET9Yf/UKpWHiEOAOwVe5gOTSgIoMm6Ri6nk/cmTkyKVgemng7perf6MGHbvf7rMhZGeCotDj8PwWhzsmlIB7WOMYUZIzBC1r1zvTiAgs8RyP8gAG0+krw3iKZmqdNU/7h0qXvPvX6RLpiaDoKE/4tPhHTFxKNkwdi3mSj+OGi9AcaHLPE1fX4OvgO0bpe4zd6A6C0FAb0keGaPcZgUQDNqZOFQ1ySZiHjgrDquaZ2XhlGsUD2A0mG4vdhGA8JvDGEbv5gppqYM7aNStactWIbVD8O+E4pa58gK0qkhnbhppgFHVDk50KQuO3usgqTqgJY/nnQzaP9kLgf+dO03kZnBK/NTeGOqiJaIaV/N8B2ryFpOpSovqPMHTLt6BPB4PppBXPXgHnAs5tPJQ/Y=
deploy:
  provider: pypi
  user: securisec
  password:
    secure: N2U4g/+AkUN1RPJmcHYocSqFZiF/Td2E21tFuk6y+tG2E2Rzyk42pgyrUsczB06lC4x3sDwbsXM6hxxa78vidYBKLdV/1B2ONf3XonHzwsyqOTyrFZKILsNumVmk4pMj7qXOJvUMC88l1WFg7MJaw6XuDjTPD6iLcs0HlCuWXzLFSxj6h0Q6hAtaoRDWE4qF+uyYOoS1DqJauQk7X8IdPZDVQRO59SwLKh/QkLQe8pux/2hETMLyn9BgGnjPIQpHKESH539pwOxYhI8tN3vl47JeI+DTo+AUMfQs+3S7K0n39BRhLKI3L09zu8Hh26X+VlJFrFHsolbk04439xy0sRteapLCJ4tCZ58GCyU2sL1nDB2qp4nMlEz5Bou5SM+x10Qc9bL4+MnCvE0v6f79qSYPDoAflRwPzwX703Dy9tZgiyHOFNks/u/aLhEHhp/KGyAv09khVkWqaeQQVIWrYnda2YXJ0xhd7gpqHgETnl3ilMbYpBXdkJwd8yS96ijBM5hPixxhdtSoi3C7aVcWoCGiS864y2gdrOkIdXYVzRz74hG097eSCph/84vBO0mjnuG094boUt/I9M4foRo+aPJN9MbSmNzqdQgGM6E7IpmOGjj4UgQiM2H6/mA1vtmwNoVOR/Qdij/iYzDRm50tssqBElx/jlxzbDJv/DTyXQw=
  on:
    tags: true
    distributions: sdist bdist_wheel
  skip_exisiting: true
  skip_cleanup: true
